-- ═══════════════════════════════════════════════════════════════════════════
-- 0000 — Schema baseline (issue #375, epic #102)
--
-- Reconstructs the full live schema as of 2026-09-18 from the repo's recorded
-- DDL: docs/06-supabase.md (base tables), the nine runtime migrations under
-- src/lib/migrations/ (001 lender preferences, 002 multisig / securitization /
-- invoice documents, 003 encrypted messages / escrow column, 004 health /
-- notifications, 005 reminders), the indexer's protocol_stats, the SEP-10
-- replay-guard table (docs/08), and the wallet_verified column add.
--
-- Targets plain Postgres 16 (the docker-compose service and Neon). Two
-- Supabase primitives are provided by a clearly-marked compatibility shim so
-- every RLS policy works unchanged:
--   * schema `auth` with a minimal `auth.users` table,
--   * `auth.uid()` reading the `request.jwt.claim.sub` setting.
-- On a Supabase project the native objects already exist and the shim is a
-- no-op (every piece is guarded). On Neon the shim provides the same shape
-- until epic #102's storage layer replaces client-side RLS access entirely
-- (ADR-0009).
--
-- Idempotent: safe to re-run. Do NOT edit this file to evolve the schema —
-- add a new numbered migration instead (see migrations/README.md).
-- ═══════════════════════════════════════════════════════════════════════════

-- ── Supabase compatibility shim ──────────────────────────────────────────────
-- Only created when absent; on Supabase the real auth schema takes precedence.

create schema if not exists auth;

create table if not exists auth.users (
  id         uuid primary key,
  email      text unique,
  created_at timestamptz not null default now()
);

-- (distinct dollar-quote tags: the function body's $uid$ is nested inside
-- the do-block's $shim$ — plain $$ would terminate the outer block)
do $shim$ begin
  if not exists (
    select 1 from pg_proc
    where proname = 'uid' and pronamespace = 'auth'::regnamespace
  ) then
    create function auth.uid() returns uuid language sql stable as $uid$
      select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid
    $uid$;
  end if;
end $shim$;

-- ═══════════════════════════════════════════════════════════════════════════
-- Base tables (docs/06-supabase.md)
-- ═══════════════════════════════════════════════════════════════════════════

-- User profiles (one row per registered user). role's final shape includes
-- 'admin' (added later by the health-monitoring migration; created directly in
-- its final form here — see migrations/README.md).
create table if not exists user_profiles (
  id              uuid primary key references auth.users(id) on delete cascade,
  email           text not null,
  role            text not null check (role in ('business', 'lender', 'admin')),
  display_name    text,
  wallet_address  text,
  -- Added by hand on the live project (docs/08-environment-variables.md):
  -- SEP-10-verified wallet vs blind-trust linked wallet.
  wallet_verified boolean not null default false,
  created_at      timestamptz not null default now()
);

-- Invoice mirror — fast-queryable copy of on-chain invoices.
create table if not exists invoices (
  id            text primary key,
  originator    text not null,             -- Stellar public key
  originator_id uuid references auth.users(id),
  amount        text not null,             -- display string (e.g. "1000.00")
  currency      text not null check (currency in ('XLM', 'USDC')),
  due_date      timestamptz not null,
  status        text not null default 'Pending'
    check (status in ('Pending', 'Financed', 'Repaid', 'Overdue', 'Cancelled')),
  created_at    timestamptz not null default now()
);

-- Financing offers mirror.
create table if not exists financing_offers (
  id            text primary key,
  invoice_id    text not null references invoices(id) on delete cascade,
  lender_id     uuid references auth.users(id),
  lender        text not null,             -- Stellar public key
  amount        text not null,
  currency      text not null check (currency in ('XLM', 'USDC')),
  interest_rate integer not null,          -- basis points (500 = 5%)
  duration      integer not null,          -- seconds
  status        text not null default 'Pending'
    check (status in ('Pending', 'Accepted', 'Rejected', 'Repaid', 'Defaulted')),
  funded_at     integer default 0,         -- unix timestamp, 0 = not funded
  created_at    timestamptz not null default now()
);

-- Secondary-market position listings (ADR-0004) — discovery only.
create table if not exists position_listings (
  id             uuid primary key default gen_random_uuid(),
  seller         text not null,            -- Stellar public key holding the position
  seller_id      uuid references auth.users(id),
  invoice_id     text not null references invoices(id) on delete cascade,
  offer_id       text references financing_offers(id) on delete set null,
  token_amount   text not null,            -- position tokens offered, e.g. "1000.00"
  asking_price   text not null,            -- what the seller wants, e.g. "950.00"
  price_currency text not null check (price_currency in ('XLM', 'USDC')),
  status         text not null default 'Open'
    check (status in ('Open', 'Settled', 'Withdrawn')),
  note           text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

-- Invoice proof documents (issue #222) — access-controlled index to files
-- pinned on IPFS (bytes live on IPFS; this stores CID + SHA-256 for tamper
-- detection). DDL from src/lib/migrations/002_invoice_documents.sql.
create table if not exists invoice_documents (
  id            uuid primary key default gen_random_uuid(),
  invoice_id    text not null references invoices(id) on delete cascade,
  uploader_id   uuid not null references auth.users(id),
  file_name     text not null,
  mime_type     text not null
    check (mime_type in ('application/pdf', 'image/jpeg', 'image/png')),
  file_size     integer not null
    check (file_size > 0 and file_size <= 10485760), -- max 10 MB
  ipfs_cid      text not null,
  document_hash text not null,                       -- SHA-256 hex of the file
  status        text not null default 'pending'
    check (status in ('pending', 'verified', 'rejected')),
  verification_comment text,
  verified_by   uuid references auth.users(id),
  verified_at   timestamptz,
  created_at    timestamptz not null default now()
);

-- ── protocol_stats (indexer; apps/indexer/README.md) ─────────────────────────
-- Singleton row (id = 1) rewritten by the indexer under the service role and
-- read publicly by the /stats page.

create table if not exists protocol_stats (
  id                 integer primary key default 1 check (id = 1),
  total_invoices     integer not null default 0,
  total_offers       integer not null default 0,
  invoices_financed  integer not null default 0,
  total_volume       text not null default '0',    -- stroops (i128 as string)
  total_repaid       text not null default '0',    -- stroops
  repayment_rate     numeric not null default 0,   -- 0..1
  active_lenders     integer not null default 0,
  defaulted_invoices integer not null default 0,
  insurance_pool     text not null default '0',    -- stroops
  last_ledger        bigint not null default 0,
  updated_at         timestamptz not null default now()
);

-- ── sep10_used_challenges (docs/08-environment-variables.md) ─────────────────
-- Replay guard for SEP-10: the UNIQUE primary key on tx_hash is what
-- claimSep10ChallengeHash (src/lib/sep10-replay-guard.ts) races on to reject a
-- replayed challenge atomically.

create table if not exists sep10_used_challenges (
  tx_hash    text primary key,
  created_at timestamptz not null default now()
);

alter table sep10_used_challenges enable row level security;

-- Supabase-specific privilege handling: RLS is enabled with no client policies
-- (anon/authenticated denied) and only the service role writes. On vanilla
-- Postgres these roles don't exist — guard so the file runs unchanged.
do $$ begin
  revoke all on table sep10_used_challenges from anon, authenticated;
exception when undefined_object then null; end $$;

do $$ begin
  grant insert on table sep10_used_challenges to service_role;
exception when undefined_object then null; end $$;

-- Portable retention helper (replaces the Supabase pg_cron schedule; call from
-- the keeper/GitHub Action on Neon — rows past the 10-minute challenge window
-- serve no replay-protection purpose).
create or replace function purge_expired_sep10_challenges()
returns integer language plpgsql as $$
declare deleted_count integer;
begin
  delete from sep10_used_challenges
  where created_at < now() - interval '1 hour';
  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

-- ═══════════════════════════════════════════════════════════════════════════
-- Base-table RLS + indexes (docs/06-supabase.md)
-- ═══════════════════════════════════════════════════════════════════════════

alter table user_profiles     enable row level security;
alter table invoices          enable row level security;
alter table financing_offers  enable row level security;
alter table position_listings enable row level security;
alter table protocol_stats    enable row level security;

-- user_profiles: each user manages their own row
drop policy if exists "own_profile_select" on user_profiles;
create policy "own_profile_select" on user_profiles
  for select using (id = auth.uid());
drop policy if exists "own_profile_insert" on user_profiles;
create policy "own_profile_insert" on user_profiles
  for insert with check (id = auth.uid());
drop policy if exists "own_profile_update" on user_profiles;
create policy "own_profile_update" on user_profiles
  for update using (id = auth.uid());

-- invoices: anyone can read, only the originator can insert/update
drop policy if exists "invoices_select" on invoices;
create policy "invoices_select" on invoices for select using (true);
drop policy if exists "invoices_insert" on invoices;
create policy "invoices_insert" on invoices
  for insert with check (originator_id = auth.uid());
drop policy if exists "invoices_update" on invoices;
create policy "invoices_update" on invoices
  for update using (originator_id = auth.uid());

-- financing_offers: anyone can read; lender inserts own; lender or the
-- invoice's originator updates.
drop policy if exists "offers_select" on financing_offers;
create policy "offers_select" on financing_offers for select using (true);
drop policy if exists "offers_insert" on financing_offers;
create policy "offers_insert" on financing_offers
  for insert with check (lender_id = auth.uid());
drop policy if exists "offers_update" on financing_offers;
create policy "offers_update" on financing_offers
  for update using (
    lender_id = auth.uid()
    or exists (
      select 1 from invoices
      where invoices.id = financing_offers.invoice_id
        and invoices.originator_id = auth.uid()
    )
  );

-- position_listings: anyone can read (discovery), only the seller writes
drop policy if exists "listings_select" on position_listings;
create policy "listings_select" on position_listings for select using (true);
drop policy if exists "listings_insert" on position_listings;
create policy "listings_insert" on position_listings
  for insert with check (seller_id = auth.uid());
drop policy if exists "listings_update" on position_listings;
create policy "listings_update" on position_listings
  for update using (seller_id = auth.uid());

-- protocol_stats: public read for the /stats page (indexer writes with the
-- service role / table owner, bypassing RLS).
drop policy if exists "public read protocol_stats" on protocol_stats;
create policy "public read protocol_stats"
  on protocol_stats for select using (true);

-- Indexes (docs/06-supabase.md)
create index if not exists invoices_originator_id_idx on invoices (originator_id);
create index if not exists invoices_status_idx on invoices (status);
create index if not exists offers_invoice_id_idx on financing_offers (invoice_id);
create index if not exists offers_lender_id_idx on financing_offers (lender_id);
create index if not exists offers_status_idx on financing_offers (status);
create index if not exists listings_status_idx on position_listings (status);
create index if not exists listings_invoice_id_idx on position_listings (invoice_id);
create index if not exists listings_seller_id_idx on position_listings (seller_id);
create index if not exists invoice_documents_invoice_id_idx on invoice_documents (invoice_id);
create index if not exists invoice_documents_uploader_id_idx on invoice_documents (uploader_id);
create index if not exists invoice_documents_status_idx on invoice_documents (status);

-- ═══════════════════════════════════════════════════════════════════════════
-- src/lib/migrations/001_lender_preferences.sql
-- ═══════════════════════════════════════════════════════════════════════════

create table if not exists lender_preferences (
  id            uuid primary key default gen_random_uuid(),
  lender_id     uuid not null references auth.users(id) on delete cascade,

  -- Risk appetite: 'conservative' | 'moderate' | 'aggressive'
  risk_profile         text not null default 'moderate'
    check (risk_profile in ('conservative', 'moderate', 'aggressive')),

  -- Currency preference: 'XLM' | 'USDC' | 'both'
  currency_preference  text not null default 'both'
    check (currency_preference in ('XLM', 'USDC', 'both')),

  -- Minimum acceptable yield in basis points (e.g. 500 = 5.00%)
  min_yield_bps        integer not null default 500
    check (min_yield_bps >= 0 and min_yield_bps <= 100000),

  -- Max / min invoice amount the lender is willing to finance (in stroops).
  -- 0 means "no restriction".
  max_amount_stroops   text not null default '0',
  min_amount_stroops   text not null default '0',

  -- Maximum days until due-date the lender will consider. 0 = no cap.
  max_due_days         integer not null default 0
    check (max_due_days >= 0),

  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- Enforce one row per lender
create unique index if not exists lender_preferences_lender_id_idx
  on lender_preferences (lender_id);

alter table lender_preferences enable row level security;

drop policy if exists "Lender can manage own preferences" on lender_preferences;
create policy "Lender can manage own preferences"
  on lender_preferences
  for all
  using  (lender_id = auth.uid())
  with check (lender_id = auth.uid());

-- Shared updated_at trigger helper (created by 001, reused by later files)
create or replace function update_updated_at_column()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists lender_preferences_updated_at on lender_preferences;
create trigger lender_preferences_updated_at
  before update on lender_preferences
  for each row execute function update_updated_at_column();

-- ═══════════════════════════════════════════════════════════════════════════
-- src/lib/migrations/002_multisig_transactions.sql (issue #219, ADR-0006)
-- ═══════════════════════════════════════════════════════════════════════════

create table if not exists pending_transactions (
  id                   uuid primary key default gen_random_uuid(),
  title                text not null,
  operation            text not null,
  initiator            text not null,
  initiator_id         uuid references auth.users(id) on delete set null,
  xdr                  text not null,
  network_passphrase   text not null,
  amount               text not null,
  currency             text not null check (currency in ('XLM', 'USDC')),
  required_signatures  integer not null default 3
    check (required_signatures >= 2),
  status               text not null default 'Pending'
    check (status in ('Pending', 'Executed', 'Rejected', 'Expired')),
  tx_hash              text,
  expires_at           timestamptz not null,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);

create table if not exists transaction_approvals (
  id                uuid primary key default gen_random_uuid(),
  pending_tx_id     uuid not null references pending_transactions(id) on delete cascade,
  approver_address  text not null,
  approver_id       uuid references auth.users(id) on delete set null,
  signature         text not null,
  created_at        timestamptz not null default now(),
  unique (pending_tx_id, approver_address)
);

create index if not exists pending_transactions_created_at_idx
  on pending_transactions (created_at desc);
create index if not exists pending_transactions_expiry_idx
  on pending_transactions (status, expires_at);
create index if not exists pending_transactions_initiator_id_idx
  on pending_transactions (initiator_id);
create index if not exists transaction_approvals_pending_tx_id_idx
  on transaction_approvals (pending_tx_id);

alter table pending_transactions  enable row level security;
alter table transaction_approvals enable row level security;

drop policy if exists "Read pending transactions" on pending_transactions;
create policy "Read pending transactions"
  on pending_transactions for select
  using (auth.uid() is not null);

drop policy if exists "Create pending transactions" on pending_transactions;
create policy "Create pending transactions"
  on pending_transactions for insert
  with check (initiator_id = auth.uid());

drop policy if exists "Participants update pending transactions" on pending_transactions;
create policy "Participants update pending transactions"
  on pending_transactions for update
  using (
    initiator_id = auth.uid()
    or exists (
      select 1 from transaction_approvals ta
      where ta.pending_tx_id = pending_transactions.id
        and ta.approver_id = auth.uid()
    )
  );

drop policy if exists "Read approvals" on transaction_approvals;
create policy "Read approvals"
  on transaction_approvals for select
  using (auth.uid() is not null);

drop policy if exists "Insert own approval" on transaction_approvals;
create policy "Insert own approval"
  on transaction_approvals for insert
  with check (approver_id = auth.uid());

drop trigger if exists pending_transactions_updated_at on pending_transactions;
create trigger pending_transactions_updated_at
  before update on pending_transactions
  for each row execute function update_updated_at_column();

-- Co-signer notification (ADR-0006 §5): emits a NOTIFY an Edge Function or
-- worker can LISTEN on; harmless when nothing is listening.
create or replace function notify_pending_transaction()
returns trigger language plpgsql as $$
begin
  perform pg_notify(
    'pending_transaction_created',
    json_build_object(
      'id', new.id,
      'title', new.title,
      'initiator', new.initiator,
      'amount', new.amount,
      'currency', new.currency,
      'required_signatures', new.required_signatures,
      'expires_at', new.expires_at
    )::text
  );
  return new;
end;
$$;

drop trigger if exists pending_transactions_notify on pending_transactions;
create trigger pending_transactions_notify
  after insert on pending_transactions
  for each row execute function notify_pending_transaction();

-- ═══════════════════════════════════════════════════════════════════════════
-- src/lib/migrations/002_securitization.sql
-- ═══════════════════════════════════════════════════════════════════════════

create table if not exists fractionalization_records (
  id                    uuid primary key default gen_random_uuid(),
  invoice_id            text  not null references invoices(id),
  originator_id         uuid  not null references auth.users(id),
  originator_address    text  not null,

  total_fractions       integer not null check (total_fractions >= 2 and total_fractions <= 1000000),
  available_fractions   integer not null
    check (available_fractions >= 0 and available_fractions <= total_fractions),
  price_per_fraction    text    not null,   -- decimal string, human units
  price_currency        text    not null check (price_currency in ('XLM', 'USDC')),

  token_symbol          text    not null,   -- e.g. "INV-001-FRAC"
  token_name            text    not null,
  decimals              integer not null default 7,

  status                text    not null default 'active'
    check (status in ('active', 'sold_out', 'cancelled')),

  description           text,

  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

create index if not exists frac_records_invoice_idx
  on fractionalization_records (invoice_id);
create index if not exists frac_records_originator_idx
  on fractionalization_records (originator_id);

-- Only one *active* fractionalization per invoice at a time.
create unique index if not exists one_active_per_invoice
  on fractionalization_records (invoice_id)
  where status in ('active', 'sold_out');

create table if not exists fractional_positions (
  id                           uuid primary key default gen_random_uuid(),
  fractionalization_id         uuid not null references fractionalization_records(id),
  lender_id                    uuid not null references auth.users(id),
  lender_address               text not null,

  fraction_count               integer not null check (fraction_count > 0),
  purchase_price_per_fraction  text    not null,
  purchase_currency            text    not null check (purchase_currency in ('XLM', 'USDC')),

  status                       text    not null default 'held'
    check (status in ('held', 'sold', 'redeemed')),

  purchased_at                 timestamptz not null default now(),
  updated_at                   timestamptz not null default now(),

  constraint one_position_per_lender unique (fractionalization_id, lender_id)
);

create index if not exists frac_positions_lender_idx
  on fractional_positions (lender_id);
create index if not exists frac_positions_frac_idx
  on fractional_positions (fractionalization_id);

create table if not exists price_history (
  id                   uuid primary key default gen_random_uuid(),
  fractionalization_id uuid not null references fractionalization_records(id),
  price                text not null,
  currency             text not null check (currency in ('XLM', 'USDC')),
  volume               integer not null check (volume > 0),
  source               text not null check (source in ('primary', 'secondary')),
  recorded_at          timestamptz not null default now()
);

create index if not exists price_history_frac_idx
  on price_history (fractionalization_id, recorded_at desc);

create table if not exists dividend_distributions (
  id                   uuid primary key default gen_random_uuid(),
  fractionalization_id uuid not null references fractionalization_records(id),
  originator_id        uuid not null references auth.users(id),

  total_amount         text not null,
  currency             text not null check (currency in ('XLM', 'USDC')),
  per_fraction_amount  text not null,

  status               text not null default 'pending'
    check (status in ('pending', 'distributed', 'cancelled')),

  distributed_at       timestamptz,
  note                 text,
  created_at           timestamptz not null default now()
);

create index if not exists dividends_frac_idx
  on dividend_distributions (fractionalization_id);

alter table fractionalization_records   enable row level security;
alter table fractional_positions        enable row level security;
alter table price_history               enable row level security;
alter table dividend_distributions      enable row level security;

drop policy if exists "Anyone can read fractionalization records" on fractionalization_records;
create policy "Anyone can read fractionalization records"
  on fractionalization_records for select using (true);

drop policy if exists "Originator can create fractionalization" on fractionalization_records;
create policy "Originator can create fractionalization"
  on fractionalization_records for insert
  with check (originator_id = auth.uid());

drop policy if exists "Originator can update own fractionalization" on fractionalization_records;
create policy "Originator can update own fractionalization"
  on fractionalization_records for update
  using (originator_id = auth.uid())
  with check (originator_id = auth.uid());

drop policy if exists "Lender can read own positions" on fractional_positions;
create policy "Lender can read own positions"
  on fractional_positions for select
  using (lender_id = auth.uid());

drop policy if exists "Lender can update own position" on fractional_positions;
create policy "Lender can update own position"
  on fractional_positions for update
  using (lender_id = auth.uid());

drop policy if exists "Anyone can read price history" on price_history;
create policy "Anyone can read price history"
  on price_history for select using (true);

-- NOTE: No insert policy for price_history — inserts are handled exclusively
-- by the security-definer RPCs below (which run as the table owner and
-- bypass RLS).

drop policy if exists "Anyone can read dividend distributions" on dividend_distributions;
create policy "Anyone can read dividend distributions"
  on dividend_distributions for select using (true);

drop policy if exists "Originator can manage dividends" on dividend_distributions;
create policy "Originator can manage dividends"
  on dividend_distributions for all
  using (originator_id = auth.uid())
  with check (originator_id = auth.uid());

drop trigger if exists fractionalization_records_updated_at on fractionalization_records;
create trigger fractionalization_records_updated_at
  before update on fractionalization_records
  for each row execute function update_updated_at_column();

drop trigger if exists fractional_positions_updated_at on fractional_positions;
create trigger fractional_positions_updated_at
  before update on fractional_positions
  for each row execute function update_updated_at_column();

-- Security-definer RPC: atomically verify availability, decrement inventory,
-- additively upsert the position, append a price-history point.
create or replace function add_fractional_position(
  p_fractionalization_id uuid,
  p_lender_id            uuid,
  p_lender_address       text,
  p_fraction_count       integer,
  p_price_per_fraction   text,
  p_currency             text
)
returns fractional_positions
language plpgsql
security definer
set search_path = public
as $$
declare
  rec fractionalization_records;
  pos fractional_positions;
  new_available integer;
begin
  -- Validate caller identity
  if auth.uid() is null or auth.uid() <> p_lender_id then
    raise exception 'Unauthorized';
  end if;

  select * into rec
    from fractionalization_records
   where id = p_fractionalization_id
     for update;

  if not found then
    raise exception 'Fractionalization not found';
  end if;

  if rec.status <> 'active' then
    raise exception 'Fractionalization is not active (status: %)', rec.status;
  end if;

  if p_fraction_count > rec.available_fractions then
    raise exception 'Only % fraction(s) available', rec.available_fractions;
  end if;

  new_available := rec.available_fractions - p_fraction_count;
  update fractionalization_records
     set available_fractions = new_available,
         status = case when new_available = 0 then 'sold_out' else 'active' end,
         updated_at = now()
   where id = p_fractionalization_id;

  insert into fractional_positions (
    fractionalization_id,
    lender_id,
    lender_address,
    fraction_count,
    purchase_price_per_fraction,
    purchase_currency,
    status,
    purchased_at
  ) values (
    p_fractionalization_id,
    p_lender_id,
    p_lender_address,
    p_fraction_count,
    p_price_per_fraction,
    p_currency,
    'held',
    now()
  )
  on conflict (fractionalization_id, lender_id) do update
    set fraction_count  = fractional_positions.fraction_count + excluded.fraction_count,
        lender_address  = excluded.lender_address,
        updated_at      = now()
  returning * into pos;

  insert into price_history (
    fractionalization_id, price, currency, volume, source, recorded_at
  ) values (
    p_fractionalization_id, p_price_per_fraction, p_currency,
    p_fraction_count, 'primary', now()
  );

  return pos;
end;
$$;

-- ═══════════════════════════════════════════════════════════════════════════
-- src/lib/migrations/002_invoice_documents.sql — RLS + verification trigger
-- (table created in the base section above)
-- ═══════════════════════════════════════════════════════════════════════════

drop policy if exists "documents_select" on invoice_documents;
create policy "documents_select" on invoice_documents
  for select using (
    auth.uid() = uploader_id
    or exists (
      select 1 from invoices i
      where i.id = invoice_documents.invoice_id
        and i.originator_id = auth.uid()
    )
    or exists (
      select 1 from financing_offers f
      where f.invoice_id = invoice_documents.invoice_id
        and f.lender_id = auth.uid()
    )
  );

drop policy if exists "documents_insert" on invoice_documents;
create policy "documents_insert" on invoice_documents
  for insert with check (
    exists (
      select 1 from invoices i
      where i.id = invoice_id
        and i.originator_id = auth.uid()
    )
  );

drop policy if exists "documents_verify" on invoice_documents;
create policy "documents_verify" on invoice_documents
  for update using (
    exists (
      select 1 from financing_offers f
      where f.invoice_id = invoice_documents.invoice_id
        and f.lender_id = auth.uid()
    )
  );

-- Verification guard: only the verification fields may change after upload,
-- and verified_by / verified_at are always stamped from the caller's session.
create or replace function enforce_document_verification_update()
returns trigger language plpgsql as $$
begin
  if new.status not in ('pending', 'verified', 'rejected') then
    raise exception 'invalid document status: %', new.status;
  end if;

  if new.status = 'pending' then
    new.verified_by = null;
    new.verified_at = null;
  else
    new.verified_by = auth.uid();
    new.verified_at = now();
  end if;

  if new.invoice_id <> old.invoice_id
    or new.uploader_id <> old.uploader_id
    or new.file_name <> old.file_name
    or new.mime_type <> old.mime_type
    or new.file_size <> old.file_size
    or new.ipfs_cid <> old.ipfs_cid
    or new.document_hash <> old.document_hash
    or new.created_at <> old.created_at
  then
    raise exception 'only the verification fields (status, verification_comment, verified_by, verified_at) may be updated';
  end if;

  return new;
end;
$$;

drop trigger if exists invoice_documents_verify_trigger on invoice_documents;
create trigger invoice_documents_verify_trigger
  before update on invoice_documents
  for each row execute function enforce_document_verification_update();

-- ═══════════════════════════════════════════════════════════════════════════
-- src/lib/migrations/003_encrypted_messages.sql (issue #228)
-- ═══════════════════════════════════════════════════════════════════════════

create table if not exists encrypted_messages (
  id                uuid primary key default gen_random_uuid(),
  invoice_id        text not null references invoices(id) on delete cascade,
  sender_address    text not null,
  recipient_address text not null,
  -- AES-256-GCM ciphertext, base64: base64(12-byte IV || ciphertext).
  encrypted_content text not null,
  message_type      text not null default 'text'
    check (message_type in ('text', 'document_ref', 'term_proposal')),
  read_at           timestamptz,
  retention_days    integer not null default 90,
  created_at        timestamptz not null default now()
);

create index if not exists encrypted_messages_invoice_id_idx
  on encrypted_messages (invoice_id, created_at asc);
create index if not exists encrypted_messages_sender_idx
  on encrypted_messages (sender_address);
create index if not exists encrypted_messages_recipient_idx
  on encrypted_messages (recipient_address);
create index if not exists encrypted_messages_retention_idx
  on encrypted_messages (created_at)
  where retention_days is not null;

alter table encrypted_messages enable row level security;

drop policy if exists "Participants can read messages" on encrypted_messages;
create policy "Participants can read messages"
  on encrypted_messages for select
  using (
    auth.uid() is not null
    and exists (
      select 1
      from user_profiles up
      where up.id = auth.uid()
        and (
          up.wallet_address = encrypted_messages.sender_address
          or up.wallet_address = encrypted_messages.recipient_address
        )
    )
  );

drop policy if exists "Sender can insert messages" on encrypted_messages;
create policy "Sender can insert messages"
  on encrypted_messages for insert
  with check (
    auth.uid() is not null
    and exists (
      select 1
      from user_profiles up
      where up.id = auth.uid()
        and up.wallet_address = encrypted_messages.sender_address
    )
  );

drop policy if exists "Recipient can mark as read" on encrypted_messages;
create policy "Recipient can mark as read"
  on encrypted_messages for update
  using (
    auth.uid() is not null
    and exists (
      select 1
      from user_profiles up
      where up.id = auth.uid()
        and up.wallet_address = encrypted_messages.recipient_address
    )
  );

-- Retention cleanup (call from a scheduled job on Neon; Supabase used pg_cron).
create or replace function purge_expired_messages()
returns integer language plpgsql
security definer
set search_path = public
as $$
declare
  deleted_count integer;
begin
  delete from encrypted_messages
  where created_at + (retention_days || ' days')::interval < now();

  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

-- ═══════════════════════════════════════════════════════════════════════════
-- src/lib/migrations/003_escrow.sql (Trustless Work disbursement rail)
-- ═══════════════════════════════════════════════════════════════════════════

alter table financing_offers
  add column if not exists escrow_contract_id text;

comment on column financing_offers.escrow_contract_id is
  'Trustless Work escrow contract id (C...) for milestone-gated disbursement; null when the direct-transfer rail was used.';

-- ═══════════════════════════════════════════════════════════════════════════
-- src/lib/migrations/004_health_monitoring.sql
-- (user_profiles.role was created in its final form — admin included — in the
--  base section; see migrations/README.md.)
-- ═══════════════════════════════════════════════════════════════════════════

create table if not exists health_metrics (
  id              bigint primary key generated always as identity,
  bucket_start    timestamptz not null,
  bucket_end      timestamptz not null,
  tx_success      integer not null default 0,
  tx_failure      integer not null default 0,
  avg_fee_stroops bigint not null default 0,
  p95_fee_stroops bigint not null default 0,
  avg_confirmation_ms integer not null default 0,
  event_counts    jsonb not null default '{}',
  contracts_active text[] not null default '{}',
  created_at      timestamptz not null default now(),
  unique (bucket_start)
);

create index if not exists health_metrics_bucket_start_idx
  on health_metrics (bucket_start desc);

create table if not exists contract_state_snapshots (
  id                    bigint primary key generated always as identity,
  snapshotted_at        timestamptz not null default now(),
  last_ledger           bigint not null default 0,
  invoices_pending      integer not null default 0,
  invoices_financed     integer not null default 0,
  invoices_repaid       integer not null default 0,
  invoices_overdue      integer not null default 0,
  invoices_defaulted    integer not null default 0,
  invoices_cancelled    integer not null default 0,
  invoices_disputed     integer not null default 0,
  total_invoices        integer not null default 0,
  insurance_pool_total  text not null default '0',
  insurance_pool_staked text not null default '0',
  position_token_supply text not null default '0',
  repayment_rate        numeric(6,4) not null default 0,
  overdue_rate          numeric(6,4) not null default 0,
  total_volume          text not null default '0',
  total_repaid          text not null default '0',
  active_lenders        integer not null default 0
);

create index if not exists contract_state_snapshots_at_idx
  on contract_state_snapshots (snapshotted_at desc);

create table if not exists alert_configs (
  id              uuid primary key default gen_random_uuid(),
  label           text not null,
  metric          text not null
    check (metric in (
      'overdue_rate', 'repayment_rate', 'tx_failure_rate',
      'insurance_pool_total', 'avg_fee_stroops', 'invoices_overdue'
    )),
  operator        text not null
    check (operator in ('gt', 'lt', 'gte', 'lte')),
  threshold       text not null,
  severity        text not null default 'warning'
    check (severity in ('info', 'warning', 'critical')),
  enabled         boolean not null default true,
  created_by      uuid references auth.users(id) on delete set null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create table if not exists audit_log (
  id          bigint primary key generated always as identity,
  action_at   timestamptz not null default now(),
  action_type text not null
    check (action_type in ('alert_breach', 'admin_action', 'config_change', 'system_event')),
  message     text not null,
  details     jsonb not null default '{}',
  severity    text not null default 'info'
    check (severity in ('info', 'warning', 'critical')),
  actor_id    uuid references auth.users(id) on delete set null,
  actor_email text
);

create index if not exists audit_log_action_at_idx
  on audit_log (action_at desc);
create index if not exists audit_log_action_type_idx
  on audit_log (action_type, action_at desc);

alter table health_metrics           enable row level security;
alter table contract_state_snapshots enable row level security;
alter table alert_configs            enable row level security;
alter table audit_log                enable row level security;

drop policy if exists "Public read health_metrics" on health_metrics;
create policy "Public read health_metrics"
  on health_metrics for select using (true);

drop policy if exists "Admin write health_metrics" on health_metrics;
create policy "Admin write health_metrics"
  on health_metrics for insert
  with check (
    exists (
      select 1 from user_profiles
      where id = auth.uid() and role = 'admin'
    )
  );

drop policy if exists "Public read snapshots" on contract_state_snapshots;
create policy "Public read snapshots"
  on contract_state_snapshots for select using (true);

drop policy if exists "Admin write snapshots" on contract_state_snapshots;
create policy "Admin write snapshots"
  on contract_state_snapshots for insert
  with check (
    exists (
      select 1 from user_profiles
      where id = auth.uid() and role = 'admin'
    )
  );

drop policy if exists "Authenticated read alert_configs" on alert_configs;
create policy "Authenticated read alert_configs"
  on alert_configs for select using (auth.uid() is not null);

drop policy if exists "Admin insert alert_configs" on alert_configs;
create policy "Admin insert alert_configs"
  on alert_configs for insert
  with check (
    exists (
      select 1 from user_profiles
      where id = auth.uid() and role = 'admin'
    )
  );

drop policy if exists "Admin update alert_configs" on alert_configs;
create policy "Admin update alert_configs"
  on alert_configs for update
  using (
    exists (
      select 1 from user_profiles
      where id = auth.uid() and role = 'admin'
    )
  );

drop policy if exists "Admin delete alert_configs" on alert_configs;
create policy "Admin delete alert_configs"
  on alert_configs for delete
  using (
    exists (
      select 1 from user_profiles
      where id = auth.uid() and role = 'admin'
    )
  );

drop policy if exists "Authenticated read audit_log" on audit_log;
create policy "Authenticated read audit_log"
  on audit_log for select using (auth.uid() is not null);

drop policy if exists "Admin insert audit_log" on audit_log;
create policy "Admin insert audit_log"
  on audit_log for insert
  with check (auth.uid() is not null);

drop trigger if exists alert_configs_updated_at on alert_configs;
create trigger alert_configs_updated_at
  before update on alert_configs
  for each row execute function update_updated_at_column();

-- ═══════════════════════════════════════════════════════════════════════════
-- src/lib/migrations/004_notifications.sql (issue #179)
-- ═══════════════════════════════════════════════════════════════════════════

create table if not exists notifications (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid references auth.users(id) on delete cascade,
  type        text not null
    check (type in (
      'offer_received',
      'offer_accepted',
      'invoice_repaid',
      'invoice_cancelled',
      'invoice_overdue',
      'offer_rejected',
      'invoice_defaulted'
    )),
  title       text not null,
  body        text not null default '',
  payload     jsonb not null default '{}'::jsonb,
  read_at     timestamptz,
  created_at  timestamptz not null default now()
);

create index if not exists notifications_user_idx
  on notifications (user_id, read_at, created_at desc);
create index if not exists notifications_unread_idx
  on notifications (user_id)
  where read_at is null;

alter table notifications enable row level security;

drop policy if exists "Users can read own notifications" on notifications;
create policy "Users can read own notifications"
  on notifications for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own notifications" on notifications;
create policy "Users can insert own notifications"
  on notifications for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own notifications" on notifications;
create policy "Users can update own notifications"
  on notifications for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own notifications" on notifications;
create policy "Users can delete own notifications"
  on notifications for delete
  using (auth.uid() = user_id);

-- ═══════════════════════════════════════════════════════════════════════════
-- src/lib/migrations/005_invoice_reminders.sql (issue #224)
-- ═══════════════════════════════════════════════════════════════════════════

create table if not exists invoice_reminders (
  id            uuid primary key default gen_random_uuid(),
  invoice_id    text not null references invoices(id) on delete cascade,
  stage         text not null
    check (stage in ('due_in_7', 'due_in_1', 'due_today', 'overdue_1', 'overdue_7')),
  channel       text not null
    check (channel in ('email', 'webhook')),
  status        text not null
    check (status in ('sent', 'failed', 'skipped')),
  recipient     text,
  attempts      integer not null default 1,
  error         text,
  created_at    timestamptz not null default now()
);

-- Duplicate-send guard: at most one row per (invoice, stage, channel).
create unique index if not exists invoice_reminders_dedupe_idx
  on invoice_reminders (invoice_id, stage, channel);

create index if not exists invoice_reminders_invoice_id_idx
  on invoice_reminders (invoice_id);
create index if not exists invoice_reminders_created_at_idx
  on invoice_reminders (created_at desc);

create table if not exists invoice_reminder_preferences (
  invoice_id  text primary key references invoices(id) on delete cascade,
  opted_out   boolean not null default false,
  updated_at  timestamptz not null default now()
);

create table if not exists reminder_configs (
  id                  smallint primary key default 1 check (id = 1),
  enabled             boolean not null default true,
  stages              jsonb not null default
    '["due_in_7", "due_in_1", "due_today", "overdue_1", "overdue_7"]',
  webhook_url         text,
  webhook_secret      text,
  max_webhook_attempts integer not null default 3
    check (max_webhook_attempts between 1 and 10),
  updated_at          timestamptz not null default now(),
  updated_by          uuid references auth.users(id)
);

insert into reminder_configs (id) values (1) on conflict (id) do nothing;

alter table invoice_reminders enable row level security;
alter table invoice_reminder_preferences enable row level security;
alter table reminder_configs enable row level security;

drop policy if exists "Originator read invoice_reminders" on invoice_reminders;
create policy "Originator read invoice_reminders"
  on invoice_reminders for select
  using (
    exists (
      select 1 from invoices
      where invoices.id = invoice_reminders.invoice_id
        and invoices.originator_id = auth.uid()
    )
    or exists (
      select 1 from user_profiles
      where id = auth.uid() and role = 'admin'
    )
  );

drop policy if exists "Originator read reminder_preferences" on invoice_reminder_preferences;
create policy "Originator read reminder_preferences"
  on invoice_reminder_preferences for select
  using (
    exists (
      select 1 from invoices
      where invoices.id = invoice_reminder_preferences.invoice_id
        and invoices.originator_id = auth.uid()
    )
    or exists (
      select 1 from user_profiles
      where id = auth.uid() and role = 'admin'
    )
  );

drop policy if exists "Originator upsert reminder_preferences" on invoice_reminder_preferences;
create policy "Originator upsert reminder_preferences"
  on invoice_reminder_preferences for insert
  with check (
    exists (
      select 1 from invoices
      where invoices.id = invoice_reminder_preferences.invoice_id
        and invoices.originator_id = auth.uid()
    )
  );

drop policy if exists "Originator update reminder_preferences" on invoice_reminder_preferences;
create policy "Originator update reminder_preferences"
  on invoice_reminder_preferences for update
  using (
    exists (
      select 1 from invoices
      where invoices.id = invoice_reminder_preferences.invoice_id
        and invoices.originator_id = auth.uid()
    )
  );

drop policy if exists "Admin read reminder_configs" on reminder_configs;
create policy "Admin read reminder_configs"
  on reminder_configs for select
  using (
    exists (
      select 1 from user_profiles
      where id = auth.uid() and role = 'admin'
    )
  );

drop policy if exists "Admin update reminder_configs" on reminder_configs;
create policy "Admin update reminder_configs"
  on reminder_configs for update
  using (
    exists (
      select 1 from user_profiles
      where id = auth.uid() and role = 'admin'
    )
  );
